<?php
/**
 * PGv2EBalancePayment
 *
 * PHP version 5
 *
 * @category Class
 * @package  BenefitPlus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Benefit Plus payment gate API (version 2)
 *
 * OpenAPI dokumentace k [Platební bráně Benefit Plus v2](https://benefit-kelnero.atlassian.net/wiki/spaces/NPBBP/pages/1125646355/Dokumentace+k+nov+platebn+br+n+pro+e-shopy+v2).
 *
 * OpenAPI spec version: 2.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BenefitPlus\Model;
use \BenefitPlus\ObjectSerializer;

/**
 * PGv2EBalancePayment Class Doc Comment
 *
 * @category Class
 * @description Enum slouží pro určení typu doplatku. Zasílá se textový klíč (např. “OneClickSync“), nikoli číslo. [Online dokumentace je dostupná zde](https://benefit-kelnero.atlassian.net/wiki/spaces/BP/pages/1214382108/Enum+PGv2+E+BalancePayment)
 * @package  BenefitPlus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PGv2EBalancePayment
{
    /**
     * Possible values of this enum
     */
    const WO_BALANCE_PAYMENT = 'WOBalancePayment';
const ONE_CLICK_SYNC = 'OneClickSync';
const PAYMENT_GATE = 'PaymentGate';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WO_BALANCE_PAYMENT,
self::ONE_CLICK_SYNC,
self::PAYMENT_GATE,        ];
    }
}
