<?php
/**
 * PGv2EPaymentState
 *
 * PHP version 5
 *
 * @category Class
 * @package  BenefitPlus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Benefit Plus payment gate API (version 2)
 *
 * OpenAPI dokumentace k [Platební bráně Benefit Plus v2](https://benefit-kelnero.atlassian.net/wiki/spaces/NPBBP/pages/1125646355/Dokumentace+k+nov+platebn+br+n+pro+e-shopy+v2).
 *
 * OpenAPI spec version: 2.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BenefitPlus\Model;
use \BenefitPlus\ObjectSerializer;

/**
 * PGv2EPaymentState Class Doc Comment
 *
 * @category Class
 * @description Enum slouží pro určení stavu platby. Používá se textový klíč enumu (např. “New“), nikoli číselná hodnota. [Online dokumentace je dostupná zde](https://benefit-kelnero.atlassian.net/wiki/spaces/BP/pages/1186660400/Enum+PGv2+E+PaymentState)
 * @package  BenefitPlus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PGv2EPaymentState
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'Unknown';
const _NEW = 'New';
const REQUIRED_ACCOUNT_PAYMENT = 'RequiredAccountPayment';
const REQUIRED_CARD_PAYMENT = 'RequiredCardPayment';
const AUTHORIZED = 'Authorized';
const CANCELED = 'Canceled';
const CANCELED_BY_E_SHOP = 'CanceledByEShop';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
self::_NEW,
self::REQUIRED_ACCOUNT_PAYMENT,
self::REQUIRED_CARD_PAYMENT,
self::AUTHORIZED,
self::CANCELED,
self::CANCELED_BY_E_SHOP,        ];
    }
}
