<?php
/**
 * PGv2PreOrderResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BenefitPlus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Benefit Plus payment gate API (version 2)
 *
 * OpenAPI dokumentace k [Platební bráně Benefit Plus v2](https://benefit-kelnero.atlassian.net/wiki/spaces/NPBBP/pages/1125646355/Dokumentace+k+nov+platebn+br+n+pro+e-shopy+v2).
 *
 * OpenAPI spec version: 2.2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BenefitPlus;

/**
 * PGv2PreOrderResultTest Class Doc Comment
 *
 * @category    Class
 * @description DTO slouží pro vrácení informací o virtuální objednávce, tj. vrací vyhodnocení možnosti založení objednávky. [Online dokumentace je dostupná zde](https://benefit-kelnero.atlassian.net/wiki/spaces/BP/pages/1125646444/DTO+PGv2+PreOrder+Result)
 * @package     BenefitPlus
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PGv2PreOrderResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PGv2PreOrderResult"
     */
    public function testPGv2PreOrderResult()
    {
    }

    /**
     * Test attribute "eshop_order_guid"
     */
    public function testPropertyEshopOrderGuid()
    {
    }

    /**
     * Test attribute "eshop_payment_guid"
     */
    public function testPropertyEshopPaymentGuid()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "pc_payment_price"
     */
    public function testPropertyPcPaymentPrice()
    {
    }

    /**
     * Test attribute "marketplace_name"
     */
    public function testPropertyMarketplaceName()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "pc_currency"
     */
    public function testPropertyPcCurrency()
    {
    }

    /**
     * Test attribute "wallets"
     */
    public function testPropertyWallets()
    {
    }
}
