<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BenefitPlus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Benefit Plus payment gate API (version 2)
 *
 * OpenAPI dokumentace k [Platební bráně Benefit Plus v2](https://benefit-kelnero.atlassian.net/wiki/spaces/NPBBP/pages/1125646355/Dokumentace+k+nov+platebn+br+n+pro+e-shopy+v2).
 *
 * OpenAPI spec version: 2.1.8
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BenefitPlus;

use BenefitPlus\Configuration;
use BenefitPlus\ApiException;
use BenefitPlus\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  BenefitPlus
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for eshopsEshopGUIDEshopordersEshopOrderGUIDCancelPost
     *
     * Stornování objednávky ze strany eshopu..
     *
     */
    public function testEshopsEshopGUIDEshopordersEshopOrderGUIDCancelPost()
    {
    }

    /**
     * Test case for eshopsEshopGUIDEshopordersEshopOrderGUIDGet
     *
     * Zjištění stavu objednávky ze strany eshopu..
     *
     */
    public function testEshopsEshopGUIDEshopordersEshopOrderGUIDGet()
    {
    }

    /**
     * Test case for eshopsEshopGUIDEshopordersPost
     *
     * Zaregistrování objednávky ze strany eshopu..
     *
     */
    public function testEshopsEshopGUIDEshopordersPost()
    {
    }

    /**
     * Test case for uiConfirmPost
     *
     * Pokusí se již existující objednávku zaplatit..
     *
     */
    public function testUiConfirmPost()
    {
    }

    /**
     * Test case for uiNewconfirmcodePost
     *
     * Zašle zákazníkovi nový potvrzovací kód (SMS zprávu) k již existující objednávce..
     *
     */
    public function testUiNewconfirmcodePost()
    {
    }

    /**
     * Test case for uiOrderPost
     *
     * Vytvoří objednávku..
     *
     */
    public function testUiOrderPost()
    {
    }

    /**
     * Test case for uiPreorderPost
     *
     * Nasimuluje vytvoření objednávky..
     *
     */
    public function testUiPreorderPost()
    {
    }
}
